language: cpp
sudo: false 

addons:
  apt:
    sources:
      # The Travis apt source whitelist can be found here:
      # https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
      - ubuntu-toolchain-r-test           # for gcc, glibc, libstdc++ at various versions
      - llvm-toolchain-precise-3.8        # clang-3.8
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data
      - ninja-build
      - g++-4.9                     # a wide-spread gcc
      - clang-3.8                   # a recent clang

compiler:
  - clang
  - gcc

install:
  # Setup the environment such that the correct compilers are chosen
  # The first arg gives the gcc version, the second the clang version.
  #- source ci/travis/install.sh "gcc-4.9" "clang-3.8"
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.8" CC="clang-3.8"; fi

env:
  global:
    - CORES=1           # Only use one core for build
    - TESTCASE=""       # Run all testcases.
  matrix:
    - BUILD_TYPE=Release
    - BUILD_TYPE=Debug

script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -GNinja ..
  - cmake --build  . -- -j ${CORES}
  - ctest --output-on-failure -R $TESTCASE
