language: cpp
sudo: false 

compiler:
        - clang
        - gcc

env:
        - BUILD_TYPE=Debug
        - BUILD_TYPE=Release

script:
        - mkdir build && cd build
        - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -GNinja ..
        - cmake --build  . -j 1
        - ctest --output-on-failure
