language: cpp
sudo: false 
os:
  - linux

env:
  global:
    - CORES=1
    - BUILD_TYPE=Release

#
# Matrix of compilers:
#
matrix:
  include:
    # Clang 3.5 & default config
    - addons: &defaultaddons
        apt:
          sources:
            # The Travis apt source whitelist can be found here:
            # https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
            - ubuntu-toolchain-r-test     # for gcc, glibc, libstdc++ at various versions
            - llvm-toolchain-precise-3.5  # for clang-3.5
            - llvm-toolchain-precise-3.8  # for clang-3.8
            - kalakris-cmake              # for cmake-2.8.11.2
          packages:
            - cmake
            - ninja-build
            - g++-4.9
            - g++-5
            - clang-3.5
            - clang-3.8
      compiler: clang
      env: COMPILER_VERSION=3.5
    
    # Clang 3.8
    - addons: *defaultaddons
      compiler: clang
      env: COMPILER_VERSION=3.8
    
    # Gcc 4.9
    - addons: *defaultaddons
      compiler: gcc
      env: COMPILER_VERSION=4.9
    
    # Gcc 5
    - addons: *defaultaddons
      compiler: gcc
      env: COMPILER_VERSION=5

script:
  - mkdir build && cd build
  - export CC="${CC}-${COMPILER_VERSION}"
  - export CXX="${CXX}-${COMPILER_VERSION}"
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -GNinja ..
  - cmake --build  . -- -j ${CORES}
  - ctest --output-on-failure
