language: cpp
sudo: false 

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.5
      - kalakris-cmake
    packages:
      - cmake
      - ninja-build
      - g++-4.9
      - clang-3.5

compiler:
  - clang
  - gcc

env:
  - BUILD_TYPE=Release CORES=1
  - BUILD_TYPE=Debug CORES=1

script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -GNinja ..
  - cmake --build  . -- -j ${CORES}
  - ctest --output-on-failure
