language: cpp
sudo: false 

install:
  # Setup the environment such that the correct compilers are chosen
  # The first arg gives the gcc version, the second the clang version.
  - source ci/travis/travis_install.sh "gcc-4.9" "clang-3.8"

addons:
  apt:
    sources:
      # The Travis apt source whitelist can be found here:
      # https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
      - ubuntu-toolchain-r-test     # for gcc, glibc, libstdc++ at various versions
      - llvm-toolchain-precise-3.8  # for clang-3.8
      - kalakris-cmake              # for cmake-2.8.11.2
    packages:
      - cmake
      - ninja-build
      - g++-4.9
      - clang-3.8

compiler:
  - clang
  - gcc

env:
  global:
    - CORES=1           # Only use one core for build
    - TESTCASE=""       # Run all testcases.
  matrix:
    - BUILD_TYPE=Release
    - BUILD_TYPE=Debug

script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -GNinja ..
  - cmake --build  . -- -j ${CORES}
  - ctest --output-on-failure -R $TESTCASE
